### ISSUE TITLE
No colors in VS 2022

### ISSUE THREAD

**Issue by zeldomar** [mike-ward/VSColorOutput64#5]
Hello,
Since switching from VS 2019 to VS 2022, I no longer have any colors in my output window. The build report is displayed fine, so the extension is active.
I tried to disable R# and other extensions, unsuccessfully.
The extension was installed directly from the "Extensions" menu in VS.

Do you have an idea to make this essential extension work again?

Thank you

**Comment by zeldomar** [comment]
That worked, many thanks !

**Comment by lu230601** [comment]
Awesome, thanks, finally worked
