### ISSUE TITLE
Are there plans to support VS 2022 ARM64? Windows 11 On arm

### ISSUE THREAD

**Issue by joesdu** [mike-ward/VSColorOutput64#6]
Are there plans to support VS 2022 ARM64? Windows 11 On arm

**Comment by mike-ward** [comment]
Kind of depends on Microsoft. If they don't make it a PIA to port and I can get an ARM system for cheap.

**Comment by joesdu** [comment]
https://github.com/mike-ward/VSColorOutput64/pull/7

**Comment by mike-ward** [comment]
Merged. Thanks!
